# Generated by Django 3.1.3 on 2020-12-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('trade_date', models.DateTimeField()),
                ('ts_code', models.CharField(max_length=9)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('pre_close', models.FloatField()),
                ('change', models.FloatField()),
                ('pct_chg', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
                ('turnover_rate', models.FloatField()),
                ('volume_ratio', models.FloatField()),
                ('ma5', models.FloatField()),
                ('ma_v_5', models.FloatField()),
                ('ma10', models.FloatField()),
                ('ma_v_10', models.FloatField()),
                ('ma20', models.FloatField()),
                ('ma_v_20', models.FloatField()),
                ('ma72', models.FloatField()),
                ('ma_v_72', models.FloatField()),
                ('ma120', models.FloatField()),
                ('ma_v_120', models.FloatField()),
            ],
            options={
                'db_table': 'stock_template',
                'ordering': ['trade_date'],
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9)),
                ('symbol', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('industry', models.CharField(max_length=45)),
                ('list_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stock_list',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.question')),
            ],
        ),
    ]
