# Generated by Django 3.1.3 on 2020-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9)),
                ('symbol', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('industry', models.CharField(max_length=45)),
                ('list_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stock_list',
            },
        ),
    ]
